version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    networks:
      - minha-network

  aplicacao:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: aplicacao
    networks:
      - minha-network
    ports:
      - "5000:5000"

networks:
  minha-network:
    driver: bridge